<?php

/** @var \Magento\Framework\View\Element\Template $block */
/** @var $listSize \Harriswebworks\Sizing\ViewModel\Size\ListSize */
$listSize = $block->getData('listSize');
/** @var $formatter \Harriswebworks\Sizing\ViewModel\Formatter */
$formatter = $block->getData('formatter');
/** @var $sizeUrl \Harriswebworks\Sizing\ViewModel\Size\Url */
$sizeUrl = $block->getData('sizeUrl');

/** @var $systemConfig \Harriswebworks\Sizing\ViewModel\SystemConfig */
$systemConfig = $block->getData('systemConfig');
?>
<?php
    $MIN_COUNT = 10;
?>
<?php if ($systemConfig): ?>
    <div class="short-description">
        <?= $systemConfig->getShortDescription(); ?>
    </div>
<?php endif; ?>

<?php if ($listSize): ?>
    <?php $sizes = $listSize->getCollection();?>
    <?php $totalCount = $sizes->getSize(); ?>
    <?php if ($totalCount): ?>
        <?php if ($totalCount > $MIN_COUNT ): ?>
            <?php $pagerHtml = $listSize->getPagerHtml(); ?>
            <div class="size-toolbar toolbar top"><?= $pagerHtml; ?></div>
        <?php endif ?>
        <div class="size-list">
            <?php
            $serial = 0;
            ?>
            <?php foreach ($sizes as $size): ?>
                <?php
                $serial++;
                ?>
                <?php /** @var \Harriswebworks\Sizing\Model\Size $size */?>
                <div class="size-item">
                    <div class="size-size">
                        <?php if ($sizeUrl): ?>
                            <a href="<?= $block->escapeUrl($sizeUrl->getSizeUrl($size, $serial)); ?>">
                                <span><?= $block->escapeHtml($size->getSize()); ?></span>
                            </a>
                        <?php else: ?>
                            <span><?= $block->escapeHtml($size->getSize()); ?></span>
                        <?php endif;?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($totalCount > $MIN_COUNT ): ?>
            <div class="size-toolbar toolbar bottom"><?= $pagerHtml; ?></div>
        <?php endif ?>
    <?php else: ?>
            <?= $block->escapeHtml(__('There are no Sizes at this moment')); ?>
    <?php endif ?>
<?php endif;
